### ISSUE TITLE
VICE Xplus4 prg games dont start

### ISSUE THREAD

**Issue by apison** [libretro/vice-libretro#478] opened 2022-09-14 18:09 UTC
Xvic issue has been fixed with #477, but vice xplus 4 has the same problem, prg file dont start the first time you launch it, in order to make them start, after you have launched it ,you must change the reset type and then restart the core.
I've tried the android build.

**Comment by sonninnos** [comment] 2022-09-14 18:36
Working fine here. Show log.

**Comment by sonninnos** [comment] 2022-09-14 19:59
I found more problem cases in D64 form that did not autostart properly, but pushed a fix, so please test.

**Comment by apison** [comment] 2022-09-15 06:44
No it doesnt work, i always need to reset te core to load the rom, this is my log :

Using old --libretro behavior. Setting libretro_directory to "/data/user/0/com.retroarch.aarch64/cores/" instead.
RetroArch 1.10.3 (Git ce8389d)
=== Build =======================================
Funzionalità:  ASIMD
[INFO] Built: Sep 13 2022
[INFO] Version: 1.10.3
[INFO] Git: ce8389d
[INFO] =================================================
[Input]: Found input driver: "android".
[Environ]: SET_PIXEL_FORMAT: RGB565.
[Core]: Versione delle API di libretro: 1, Compilato contro API: 1
[Audio]: Set audio input rate to: 48000.00 Hz.
[Video]: Set video size to: 960x720.
[Video]: Starting threaded video driver ...
[Vulkan]: Vulkan dynamic library loaded.
[Vulkan]: Found vulkan context: "vk_android".
[Vulkan]: Detecting screen resolution: 0x0.
[Vulkan]: Setting swap interval: 1.
[Android]: Native window size: 2160 x 1080.
[Vulkan]: Created Android surface: 512900821744
[Vulkan]: Found GPU at index 0: "Adreno (TM) 640".
[Vulkan]: Using GPU index 0.
[Vulkan]: Using semaphores for WSI acquire.
[Vulkan]: Using GPU: "Adreno (TM) 640".
[Vulkan]: Queue family 0 supports 3 sub-queues.
[Vulkan]: Got 3 swapchain images.
[Vulkan]: Using resolution 2160x1080.
[Vulkan]: Using RGB565 format.
[Vulkan]: Loading stock shader.
[Joypad]: Found joypad driver: "android".
[Video]: Found display server: "android".
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 1920, Blocks = 13, Total = 24960 ...
[Display]: Found display driver: "vulkan".
[SRAM]: La SRAM non verrà salvata.
[Playlist]: Caricamento dei file della cronologia: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_history.lpl".
[Playlist]: Caricamento dei file della cronologia: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_music_history.lpl".
[Playlist]: Caricamento dei file della cronologia: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_image_history.lpl".
[Playlist]: Caricamento file preferiti: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_favorites.lpl".
[Android]: Native window size: 2160 x 1080.
[Android]: Native window size: 2160 x 1080.
Threaded video stats: Frames pushed: 770, Frames dropped: 0.
[Audio]: Set audio input rate to: 48000.00 Hz.
[Video]: Set video size to: 960x720.
[Video]: Starting threaded video driver ...
[Vulkan]: Vulkan dynamic library loaded.
[Vulkan]: Found vulkan context: "vk_android".
[Vulkan]: Detecting screen resolution: 0x0.
[Vulkan]: Setting swap interval: 1.
[Android]: Native window size: 1080 x 2160.
[Vulkan]: Created Android surface: 512900511328
[Vulkan]: Found GPU at index 0: "Adreno (TM) 640".
[Vulkan]: Using GPU index 0.
[Vulkan]: Using semaphores for WSI acquire.
[Vulkan]: Using GPU: "Adreno (TM) 640".
[Vulkan]: Queue family 0 supports 3 sub-queues.
[Vulkan]: Got 3 swapchain images.
[Vulkan]: Using resolution 1080x2160.
[Vulkan]: Using RGB565 format.
[Vulkan]: Loading stock shader.
[Joypad]: Found joypad driver: "android".
[Video]: Found display server: "android".
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 1920, Blocks = 13, Total = 24960 ...
[Display]: Found display driver: "vulkan".
[Input]: Game Focus => OFF
[Android]: Resizing (1080 x 2160) -> (2160 x 1080).
[Android]: Native window size: 2160 x 1080.
[Core]: Using content: "/storage/1EB9-597E/roms/Commodore - C16.C116.Plus/Commodore C16, C116 & Plus-4 - Games - [PRG]/3D Quasars (1986)(Solar Software)(GB)[a].zip".
[Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[Core]: Unloading core..
[Core]: Unloading core symbols..
Threaded video stats: Frames pushed: 3953, Frames dropped: 0.
RetroArch 1.10.3 (Git ce8389d)
=== Build =======================================
Funzionalità:  ASIMD
[INFO] Built: Sep 13 2022
[INFO] Version: 1.10.3
[INFO] Git: ce8389d
[INFO] =================================================
[Input]: Found input driver: "android".
[Core]: Loading dynamic libretro core from: "/data/user/0/com.retroarch.aarch64/cores/vice_xplus4_libretro_android.so"
[Environ]: SYSTEM_DIRECTORY: "/storage/emulated/0/RetroArch/system".
[Environ]: CORE_ASSETS_DIRECTORY: "/storage/emulated/0/RetroArch/downloads".
[Environ]: GET_SAVE_DIRECTORY.
[Environ]: GET_CORE_OPTIONS_VERSION.
[Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2.
[Environ]: SET_CONTROLLER_INFO.
[Environ]: SET_SUPPORT_NO_GAME: yes.
[Environ]: GET_LED_INTERFACE.
[Environ]: GET_VFS_INTERFACE. Core requested version >= V1, providing V3.
[Remaps]: Core-specific remap found at "/storage/emulated/0/RetroArch/config/remaps/VICE xplus4/VICE xplus4.rmp".
[Overrides]: Reindirizzare il file di salvataggio su "/storage/emulated/0/RetroArch/saves/3D Quasars (1986)(Solar Software)(GB)[a].srm".
[Overrides]: Reindirizzare il salva stato su "/storage/emulated/0/RetroArch/states/3D Quasars (1986)(Solar Software)(GB)[a].state".
[Environ]: GET_LOG_INTERFACE.
[Environ]: GET_PERF_INTERFACE.
[Environ]: SYSTEM_DIRECTORY: "/storage/emulated/0/RetroArch/system".
[Environ]: CORE_ASSETS_DIRECTORY: "/storage/emulated/0/RetroArch/downloads".
[Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[Environ]: SET_SERIALIZATION_QUIRKS.
[Environ]: SET_INPUT_DESCRIPTORS:
[Environ]: SET_KEYBOARD_CALLBACK.
[Environ]: SET_SUPPORT_ACHIEVEMENTS: yes.
[Content]: Il caricamento del contenuto è stato saltato. Le Implemenzioni verranno caricati in proprio.
[Environ]: SET_PIXEL_FORMAT: RGB565.
Unzip: /storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg
->M3U: /storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].m3u
M3U/VFL parsed, 1 file(s) found
Arg0: xplus4
Arg1: /storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg
No configuration file found at '/storage/emulated/0/RetroArch/saves/3D Quasars (1986)(Solar Software)(GB)[a].vicerc'.
No configuration file found at '/storage/emulated/0/RetroArch/saves/vicerc'.
No configuration file found at '/storage/emulated/0/RetroArch/system/vice/vicerc'.
--------------------------------------------------------------------------------
VICE xplus4 (PLUS4) 3.5 ce3e5bc, Sep 14 2022 20:04:29
--------------------------------------------------------------------------------
DriveROM: 2000 ROM image not found. Hardware-level 2000 emulation is not available.
DriveROM: 4000 ROM image not found. Hardware-level 4000 emulation is not available.
DriveROM: CMDHD ROM image not found. Hardware-level CMDHD emulation is not available.
Drive: Finished loading ROM images.
Sound: Available sound devices: retro
AUTOSTART: Autodetecting image type of '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'.
Filesystem Image Probe: Import GCR: Unknown GCR image version 48.
Filesystem Image: Unknown disk image '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'.
Tape: Cannot open file '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'
Sound: Opened device 'retro', speed 48000Hz, fragment size 2.67ms, buffer size 21.33ms, stereo
cartridge_attach_image: unsupported type (0000)
AUTOSTART: Loading PRG file '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg' with direct RAM injection.
AUTOSTART: Resetting the machine to autostart '*'
AUTOSTART: Turning Warp mode on.
AUTOSTART: '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg' recognized as program/p00 file.
Main CPU: starting at ($FFFC).
Main CPU: RESET.
No configuration file found at '/storage/emulated/0/RetroArch/saves/3D Quasars (1986)(Solar Software)(GB)[a].vicerc'.
No configuration file found at '/storage/emulated/0/RetroArch/saves/vicerc'.
No configuration file found at '/storage/emulated/0/RetroArch/system/vice/vicerc'.
Set resource: SoundFragmentSize => 1
Set resource: Mouse => 1
Set resource: Printer4 => 1
Set resource: AutostartPrgMode => 1
Set resource: AutostartDelayRandom => 0
Set resource: FSDeviceLongNames => 1
Set resource: TEDPaletteFile => "colodore_ted"
Set resource: TEDExternalPalette => 1
Set resource: TEDFilter => 0
Set resource: TEDPALBlur => -1
Set resource: TEDPALOddLinePhase => 1000
Set resource: TEDPALOddLineOffset => 1000
Set resource: TEDColorGamma => 2800
Set resource: TEDColorTint => 1000
Set resource: TEDColorSaturation => 1000
Set resource: TEDColorContrast => 1200
Set resource: TEDColorBrightness => 900
Set resource: UserportJoy => 0
Set resource: AutostartWarp => 1
Set resource: DriveTrueEmulation => 0
Set resource: VirtualDevices => 1
Set resource: AttachDevice8Readonly => 0
Set resource: DriveSoundEmulationVolume => 400
Set resource: DriveSoundEmulation => 1
Set resource: DriveSoundEmulationVolume => 0
Set resource: DatasetteSound => 0
Set resource: TEDAudioLeak => 0
Set resource: SidEngine => 0
Arg0: xplus4
Arg1: /storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg
AUTOSTART: Autodetecting image type of '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'.
Filesystem Image Probe: Import GCR: Unknown GCR image version 48.
Filesystem Image: Unknown disk image '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'.
Tape: Cannot open file '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'
cartridge_attach_image: unsupported type (0000)
AUTOSTART: Loading PRG file '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg' with direct RAM injection.
AUTOSTART: Resetting the machine to autostart '*'
AUTOSTART: Turning Warp mode on.
AUTOSTART: '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg' recognized as program/p00 file.
Image for autostart: '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'
Cartridge image list has 1 file(s)
Attaching first cart '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'
cartridge_attach_image: unsupported type (ffffffff)
AUTOSTART: Turned off.
[Environ]: SET_MEMORY_MAPS.
[SRAM]: Carico SRAM saltato.
[Core]: Versione delle API di libretro: 1, Compilato contro API: 1
[Audio]: Set audio input rate to: 48000.00 Hz.
[Video]: Timings deviate too much. Will not adjust. (Display = 60.00 Hz, Game = 49.86 Hz)
[Video]: Set video size to: 1194x864.
[Video]: Starting threaded video driver ...
[Vulkan]: Vulkan dynamic library loaded.
[Vulkan]: Found vulkan context: "vk_android".
[Vulkan]: Detecting screen resolution: 0x0.
[Vulkan]: Setting swap interval: 1.
[Android]: Native window size: 2160 x 1080.
[Vulkan]: Created Android surface: 512900607280
[Vulkan]: Found GPU at index 0: "Adreno (TM) 640".
[Vulkan]: Using GPU index 0.
[Vulkan]: Using semaphores for WSI acquire.
[Vulkan]: Using GPU: "Adreno (TM) 640".
[Vulkan]: Queue family 0 supports 3 sub-queues.
[Vulkan]: Got 3 swapchain images.
[Vulkan]: Using resolution 2160x1080.
[Vulkan]: Using RGB565 format.
[Vulkan]: Loading stock shader.
[Joypad]: Found joypad driver: "android".
[Video]: Found display server: "android".
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 1920, Blocks = 13, Total = 24960 ...
[Display]: Found display driver: "vulkan".
[Playlist]: Caricamento dei file della cronologia: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_history.lpl".
[Playlist]: Caricamento dei file della cronologia: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_music_history.lpl".
[Playlist]: Caricamento dei file della cronologia: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_image_history.lpl".
[Playlist]: Caricamento file preferiti: "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/content_favorites.lpl".
[Environ]: SET_SYSTEM_AV_INFO: 384x288, Aspect: 1.383, FPS: 49.86, Sample rate: 48000.00 Hz.
[Audio]: Set audio input rate to: 48000.00 Hz.
[Video]: Timings deviate too much. Will not adjust. (Display = 60.00 Hz, Game = 49.86 Hz)
[OpenSL]: Requested audio latency: 128 ms.
[OpenSL]: Setting audio latency: Block size = 1920, Blocks = 13, Total = 24960 ...
[Display]: Found display driver: "vulkan".
[Input]: Game Focus => OFF
Main CPU: RESET.
Sound: Closing device 'retro'
Sound: Opened device 'retro', speed 48000Hz, fragment size 2.67ms, buffer size 21.33ms, stereo
[Android]: Native window size: 2160 x 1080.
AUTOSTART: Restoring FileSystemDevice8 to 1.
AUTOSTART: Restoring FSDevice8ConvertP00 to 1.
AUTOSTART: Restoring FSDeviceLongNames to 1.
Set resource: VirtualDevices => 0
Set resource: VirtualDevices => 1
[Core]: Riavviato.
cartridge_attach_image: unsupported type (ffffffff)
AUTOSTART: Autodetecting image type of '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'.
Filesystem Image Probe: Import GCR: Unknown GCR image version 48.
Filesystem Image: Unknown disk image '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'.
Tape: Cannot open file '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'
cartridge_attach_image: unsupported type (0000)
AUTOSTART: Loading PRG file '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg' with direct RAM injection.
AUTOSTART: Resetting the machine to autostart '*'
AUTOSTART: Turning Warp mode on.
AUTOSTART: '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg' recognized as program/p00 file.
AUTOSTART: Autodetecting image type of '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'.
Filesystem Image Probe: Import GCR: Unknown GCR image version 48.
Filesystem Image: Unknown disk image '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'.
Tape: Cannot open file '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'
cartridge_attach_image: unsupported type (0000)
AUTOSTART: Loading PRG file '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg' with direct RAM injection.
AUTOSTART: Resetting the machine to autostart '*'
AUTOSTART: Turning Warp mode on.
AUTOSTART: '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg' recognized as program/p00 file.
Set resource: VirtualDevices => 0
Set resource: VirtualDevices => 1
Main CPU: RESET.
AUTOSTART: Autodetecting image type of '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'.
Filesystem Image Probe: Import GCR: Unknown GCR image version 48.
Filesystem Image: Unknown disk image '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'.
Tape: Cannot open file '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg'
cartridge_attach_image: unsupported type (0000)
AUTOSTART: Loading PRG file '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg' with direct RAM injection.
AUTOSTART: Resetting the machine to autostart '*'
AUTOSTART: Turning Warp mode on.
AUTOSTART: '/storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg' recognized as program/p00 file.
Main CPU: RESET.
AUTOSTART: Injecting program data at $1001 (size $2fff)
AUTOSTART: Ready
AUTOSTART: Turning Warp mode off.
AUTOSTART: Starting program.
AUTOSTART: Restoring FileSystemDevice8 to 1.
AUTOSTART: Restoring FSDevice8ConvertP00 to 1.
AUTOSTART: Restoring FSDeviceLongNames to 1.
AUTOSTART: Done.
[Config]: Salvata la nuova configurazione su "/storage/emulated/0/Android/data/com.retroarch.aarch64/files/retroarch.cfg".
[Core]: Content ran for a total of: 00 hours, 00 minutes, 19 seconds.
[Runtime]: Saving runtime log file: "/storage/emulated/0/RetroArch/playlists/logs/VICE xplus4/3D Quasars (1986)(Solar Software)(GB)[a].lrtl".
[Core]: Unloading game..
[Core]: Unloading core..
Clean: /storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].m3u
Clean: /storage/emulated/0/RetroArch/saves/TEMP/3D Quasars (1986)(Solar Software)(GB)[a].prg
[Core]: Unloading core symbols..
[Core]: Saved core options file to "/storage/emulated/0/RetroArch/config/VICE xplus4/VICE xplus4.opt".
Threaded video stats: Frames pushed: 3080, Frames dropped: 6.

**Comment by sonninnos** [comment] 2022-09-15 13:13
Ah-ha, it is caused by having the PRG zipped. Will try to fix soon.

**Comment by sonninnos** [comment] 2022-09-15 13:37
Ok, should be sorted with the latest push.

**Comment by apison** [comment] 2022-09-15 14:11
Ok thanks I'll check it out as soon as buildbot update the core.

**Closed** 2022-09-15 14:56 UTC
