### ISSUE TITLE
Auto saving of states doesn't seem to work

### ISSUE THREAD

**Issue by Zombeaver** [libretro/vice-libretro#113] opened 2019-08-13 15:53 UTC
Normal save states seem to be working (yay!) but automatic savestates and autoloading of states don't appear to work currently. Nothing seems to be saved on exit with automatic saving on, and I tried taking a manual state and renaming it from .state to .auto but it didn't load on launch.

**Comment by rsn8887** [comment] 2019-08-13 17:17
Savestates In Vice are limited because they require temp file creation. This might be the issue. Also are you sure that autosaving in Retroarch is for these kinds of savestates? It might be SRAM only.

**Comment by Zombeaver** [comment] 2019-08-13 18:05
Ordinarily if you have:

savestate_auto_load = "true"
savestate_auto_save = "true"

In retroarch.cfg / an override, it will save a state when Retroarch exits and will load that state as soon as the game is loaded again. It creates a file named [game name].state.auto. It doesn't seem to save on exit in the Vice core though.

I should correct what I said earlier, however, autoloading _does_ work, once you rename a normal savestate appropriately. I had incorrectly changed the state name from [game name].state to [game name].auto, when it's supposed to be [game name].state.auto. If I use the correct name format, it does indeed load them on start.

**Comment by rsn8887** [comment] 2019-08-13 19:20
Congratulations you found a bug in Retroarch! The core is fine, but Retroarch disables auto save state internally whenever a core supports contentless operation. I am 100% sure this is unintended behavior. Just because a core CAN be started without content, it doesn't mean auto save state should be skipped completely for those cores. But that's how Retroarch acts atm.

I filed a bug report:
https://github.com/libretro/RetroArch/issues/9300

**Comment by Zombeaver** [comment] 2019-08-13 19:55
Ah ha! Very interesting! I would not have anticipated that it was the result of contentless start support. Yeah, I can't imagine that that's really intentional. Well, happy to help narrow down the issue, at least. That would affect a number of other cores like DOSBox (which doesn't currently support save states anyway, but presumably it will at some point) so hopefully that will be resolved.

Thank you for your help!

**Comment by rsn8887** [comment] 2019-08-14 02:57
I made a Pull Request to Retroarch to fix this issue today. As soon as it is merged, it should work.

https://github.com/libretro/RetroArch/pull/9304

**Comment by rsn8887** [comment] 2019-08-14 17:56
My PR was merged two hours ago, so auto save states should work in next nightly.

**Closed** 2019-08-14 18:07 UTC
