### ISSUE TITLE
Up arrow (keyboard) assigned to RUN/STOP

### ISSUE THREAD

**Issue by lodgerz** [libretro/vice-libretro#15] opened 2017-12-09 13:19 UTC
hi,
i can't play with keyboard because Up arrow key (PC Keyboard) is assigned to RUN/STOP (c64 keyboard), why?

**Comment by r-type** [comment] 2017-12-14 22:25
I assume you don't choose vice keyboard in control option?

**Comment by lodgerz** [comment] 2017-12-15 12:46
in control option i set "Retropad" for "User 1 and 2 Device Type". the issue occurs on both my 2 PCs.

```
$ cat ~/.config/retroarch/config/remaps/VICE\ x64/VICE\ x64.rmp 
input_player1_b = "8"
input_player1_a = "0"
input_libretro_device_p1 = "1"
input_player1_analog_dpad_mode = "0"
input_libretro_device_p2 = "1"
input_player2_analog_dpad_mode = "0"
input_libretro_device_p3 = "1"
input_player3_analog_dpad_mode = "0"
input_libretro_device_p4 = "1"
input_player4_analog_dpad_mode = "0"
input_libretro_device_p5 = "1"
input_player5_analog_dpad_mode = "0"
input_libretro_device_p6 = "1"
input_player6_analog_dpad_mode = "0"
input_libretro_device_p7 = "1"
input_player7_analog_dpad_mode = "0"
```

```
$ cat ~/.config/retroarch/retroarch-core-options.cfg|grep vice
vice_Statusbar = "disabled"
vice_Drive8Type = "1542"
vice_DriveTrueEmulation = "disabled"
vice_SidModel = "6581F"
vice_C64Model = "C64MODEL_UNKNOWN"
vice_RetroJoy = "enabled"
vice_Controller = "joystick"
vice_mapper_y = "RETROK_F9"
vice_mapper_x = "RETROK_EURO"
vice_mapper_b = "RETROK_EURO"
vice_mapper_l2 = "RETROK_EURO"
vice_mapper_r2 = "RETROK_EURO"
vice_mapper_l3 = "RETROK_EURO"
vice_mapper_r3 = "RETROK_EURO"
vice_mapper_l = "RETROK_ESCAPE"
vice_mapper_r = "RETROK_RETURN"
vice_mapper_start = "RETROK_SPACE"
```

**Comment by r-type** [comment] 2017-12-15 18:32
if you want play with keyboard , choose vice keyboard from controller option instead of joypad.
or in menu core option choose  vice_Controller: to keyboard.

**Comment by lodgerz** [comment] 2017-12-15 18:53
i have tried to set "Vice keyboard" to "User 1 and 2 Device Type" and "Controller0 type: keyboard" on core option but still Up arrow is assigned to RUN/STOP.
then i SOLVED setting "Retro joy0: OFF" on core option.

**Comment by tukicat** [comment] 2018-01-04 09:09
@r-type Hi,

I have been doing some testing with lr-vice on my retropie and the run/stop set to "up" has caused a few issues for me. I use a USB keyboard encoder (mines and Ipac) and by deafult on a lot of these the arrow keys are set as joystick one. 

I have tried messing with the settings but I cannot seem to set up joystick so that joystick 1 "up" is not Run/Stop. Is there anyway to change the "up" key so that it does not register a Run/Stop key press?

There are a couple of us with USB keyboard encoders that are having this issue.

I am happy to share my retroarch.cfg if it helps. 

Also, thanks for sorting out the issue with "Core broken on Linux - undefined symbol: retro_opendir" this is now fixed and the installation works fine now and lr-vice runs.

**Comment by SapphireTactician** [comment] 2018-04-04 02:52
Put me down for this issue too, using Debian Linux 9 64-bit with RA 1.7.2 and was trying to play Ultimate Wizard but ran into this exact problem. Also the left arrow key sometimes doesn't respond as well.

I'm guessing some things are hard mapped to the keyboard that can't be edited with this core? When using an actual controller, all the buttons I mapped in RA work perfectly fine, but when using the keyboard to emulate a controller as per the Input Settings, I experience the same problem.

It's worth noting though that my keyboard isn't USB though, but PS/2.

**Comment by rhester72** [comment] 2018-04-07 02:35
On my RetroPie build with the latest source, up arrow results in LOAD, not RUN/STOP, but all other arrow keys function as expected.

**Comment by fturioni** [comment] 2018-05-13 14:33
Sorry for re-upping this after some month, but I googled and searched so much and found only this thread... so I would write to point that I have the same exact issue here with win10, latest retroarch and vice x64 core nightly... I am able to use the keyboard, but tried pretty much every combination in retroarch input /core config and... the up arrow key triggers run/stop and in many games this activated in game pause... also the workaround of putting retrojoy0 = OFF works here, but then you are forced to use the numpad keys... very different layout. Am I still missing some config step? Is it possible to know the correct config (driver, reatroarch, core) in case to use lr-vice with a keyboard the same manner of the other cores (arrow keys + z, x etc...) and eventually manually map the space and/or run/stop keys to another phisical key or using the virtual keyboard? Should I edit some config file? Thank you.

**Comment by Gazdaman** [comment] 2018-05-20 14:04
I think Run/Stop is also mapped to the wrong key in the virtual keyboard.
Virtual keyboard "Ctrl" is actually Run/Stop key meaning others may be messed up

**Comment by barcoboy** [comment] 2018-06-30 17:04
I too can confirm having this problem with x64.  BUT, xvic is WAY WORSE.  For example, when I hit the keys:

BACKQUOTE 1 2 3 4 5 6 7 8 9 0 - = BACKSPACE

on my keyboard (real or virtual), I get this:

ENTER DEL CRSR-DOWN 3 <nothing> 5 X 7 V 9 N + , 1

Strangely enough, there seems to be a pattern, as it is most always every second key, and only affects the top and bottom rows.  Other than Q, the QWERTY row functions normally.  Normal too with the second row, other than A and ENTER bringing up VICE GUI dialogs (the A still prints in the background, but ENTER does nothing else).  The bottom row 

SHIFT Z X C V B N M , . / SHIFT

row gives:

4 <nothing (cursor flashes)> 6 C 8 B 0 M - . HOME <nothing>

Also, I noticed that if I repeatedly push the Z key on my keyboard, occasionally I will get a Z appearing on the screen, but most of the time it just make the cursor flash (guessing it is mapped to a function key).

I have compiled VICE 3.0 on the same system and the keyboard on xvic and x64 works fine there.  I tried copying some of the .vkm files from my install and re-compiling vice-libretro, but it did not help any.

**Comment by sneaker333** [comment] 2019-02-18 15:15
I believe that there are at least 2 issues here ... there appears to be some libretro glue which sets up the keyboard matrix and code only exists for the c64 keyboard, which is why the vic20 keyboard is quite messed up. I have a code change to set the vic20 keymap (if I can work out how to use Git then hopefully I can submit that). Strangely the C64 up arrow behaviour does not occur on the vic ... and as pointed out it only happens when the retrojoy is enabled. The keymap is not at fault in this instance, somewhere the code appears to get changed to shift+runstop (which is the shortcut for load). I imagine this is probably by design, although I'm guessing a less critical key could be mapped to that instead. I'll keep looking to see if I can find out where this is happening.

**Comment by rsn8887** [comment] 2019-07-25 13:12
I think this might be fixed in tomorrow’s nightly with my merged PR. Please report if this issue can now be closed.

**Comment by rsn8887** [comment] 2019-07-25 20:17
This was an issue because keyboard joystick emulation interferes with raw keyboard presses. I fixed this in my latest PR. To make the physical keyboard work when you have retropad bindings on the keyboard (like the default on desktop machines), make sure you set Quickmenu->controls->Port 0->"Disconnected" or "Vice Keyboard". If you want to use both a physical keyboard AND a Joystick with Retropad in Port 0, you should remove the default keyboard bindings of cursor keys and A,Z keys to Retropad inputs.

This will now be like it is on ANY other core with keyboard support. Before my fix, this core behaved a bit confusingly with multiple core options to tackle these issues. I think the reason for this peculiar behavior was that this core was written before the advanced input mapper (quickmenu->controls) was available. The input mapper now provides these functionalities, so my PR removes a few obsolete core options. 
Options made obsolete buy properly using `quickmenu->controls`:
- `Retro joy0`
- `Controller0 type`

**Closed** 2019-07-25 20:32 UTC

**Comment by d3viant** [comment] 2019-10-21 07:05
What is a PR?
